### ISSUE TITLE
lib doesn't work for next 14.2

### ISSUE THREAD

**Issue by mindmind** [expatfile/next-runtime-env#123]
Hey everyone,
today I upgraded my app with new 14.2.1 next.js version and found next-runtime-env crashing my app in the development runtime:

```shell
TypeError: (0 , react_1.createContext) is not a function
    at Object.<anonymous> (/blabla/.next/server/chunks/node_modules_927e2a._.js:1942:48)
    at [project]/node_modules/next-runtime-env/build/provider/env-context.js [app-route] (ecmascript) (/blabla/.next/server/chunks/node_modules_927e2a._.js:1944:3)
    at instantiateModule (/blabla/.next/server/chunks/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/blabla/.next/server/chunks/[turbopack]_runtime.js:572:12)
    at commonJsRequire (/blabla/.next/server/chunks/[turbopack]_runtime.js:136:20)
    at Object.<anonymous> (/blabla/.next/server/chunks/node_modules_927e2a._.js:1954:23)
    at [project]/node_modules/next-runtime-env/build/provider/env-provider.js [app-route] (ecmascript) (/blabla/.next/server/chunks/node_modules_927e2a._.js:1972:3)
    at instantiateModule (/blabla/.next/server/chunks/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/blabla/.next/server/chunks/[turbopack]_runtime.js:572:12)
    at commonJsRequire (/blabla/.next/server/chunks/[turbopack]_runtime.js:136:20)
    at Object.<anonymous> (/blabla/.next/server/chunks/node_modules_927e2a._.js:2063:22)
    at [project]/node_modules/next-runtime-env/build/provider/index.js [app-route] (ecmascript) (/blabla/.next/server/chunks/node_modules_927e2a._.js:2085:3)
    at instantiateModule (/blabla/.next/server/chunks/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/blabla/.next/server/chunks/[turbopack]_runtime.js:572:12)
    at commonJsRequire (/blabla/.next/server/chunks/[turbopack]_runtime.js:136:20)
    at Object.<anonymous> (/blabla/.next/server/chunks/node_modules_927e2a._.js:2434:14)
    at [project]/node_modules/next-runtime-env/build/index.js [app-route] (ecmascript) (/blabla/.next/server/chunks/node_modules_927e2a._.js:2444:3)
    at instantiateModule (/blabla/.next/server/chunks/[turbopack]_runtime.js:520:23)
``` 
it works fine for me if I use next.js 14.1

I found that next.js swear on `import { createContext } from 'react';` and asks to add `'use client'` for it. Maybe the reason is somewhere around.

**Comment by tefkah** [comment]
Not sure if it's the right way to go about it, but I found that setting
```ts
	experimental: {
		serverComponentsExternalPackages: ["next-runtime-env"],
	}
```

seems to solve my issue.

**Comment by HofmannZ** [comment]
This seems to only be related to the context approach. The suggested patch seems to work and we've updated the example in #127.
